// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoPLyDjAsGRicbLoR601h6KzxZ2YPF-6I',
    appId: '1:735723660528:web:ce285fa17eb12c3943ce35',
    messagingSenderId: '735723660528',
    projectId: 'projects-e2877',
    authDomain: 'projects-e2877.firebaseapp.com',
    storageBucket: 'projects-e2877.firebasestorage.app',
    measurementId: 'G-72H0H4CTL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2Yv4L-9GuOhmXoiPjUlwSP7gDhKJePg',
    appId: '1:735723660528:android:59551955995685af43ce35',
    messagingSenderId: '735723660528',
    projectId: 'projects-e2877',
    storageBucket: 'projects-e2877.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3GrwGn-aLHYBveXO_FupJxnhY_22Rgk8',
    appId: '1:735723660528:ios:426f56a08379ce6143ce35',
    messagingSenderId: '735723660528',
    projectId: 'projects-e2877',
    storageBucket: 'projects-e2877.firebasestorage.app',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3GrwGn-aLHYBveXO_FupJxnhY_22Rgk8',
    appId: '1:735723660528:ios:426f56a08379ce6143ce35',
    messagingSenderId: '735723660528',
    projectId: 'projects-e2877',
    storageBucket: 'projects-e2877.firebasestorage.app',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoPLyDjAsGRicbLoR601h6KzxZ2YPF-6I',
    appId: '1:735723660528:web:2fa01a669051c9a243ce35',
    messagingSenderId: '735723660528',
    projectId: 'projects-e2877',
    authDomain: 'projects-e2877.firebaseapp.com',
    storageBucket: 'projects-e2877.firebasestorage.app',
    measurementId: 'G-WB66B5WEBE',
  );
}
